sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: pengjiahao0523

  redis:
    host: localhost
    port: 6379
    password: pengjiahao0523
    database: 1

  wechat:
    appid: wxdfb2575222ef9e39
    secret: 745105ec5235553bc576bf26e8e6e0de
